In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 


# Dataset Loading and creating copy

In [2]:
df = pd.read_csv(r'D:\Internship Project\balanced_ai_human_prompts.csv')
df

text  generated
0     Machine learning, a subset of artificial intel...          1
1     A decision tree, a prominent machine learning ...          1
2     Education, a cornerstone of societal progress,...          1
3     Computers, the backbone of modern technology, ...          1
4     Chess, a timeless game of strategy and intelle...          1
...                                                 ...        ...
2745  Generate a detailed summary of global healthca...          1
2746  Compose an in-depth exploration of financial t...          1
2747  Generate a detailed summary of autonomous vehi...          1
2748  Develop a persuasive argument about internet o...          1
2749  Generate a detailed summary of supply chain ma...          1

[2750 rows x 2 columns]

In [3]:
df.describe()

generated
count  2750.000000
mean      0.500000
std       0.500091
min       0.000000
25%       0.000000
50%       0.500000
75%       1.000000
max       1.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2750 entries, 0 to 2749
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   text       2750 non-null   object
 1   generated  2750 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 43.1+ KB


In [5]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [6]:
data = df.copy()
data

text  generated
0     Machine learning, a subset of artificial intel...          1
1     A decision tree, a prominent machine learning ...          1
2     Education, a cornerstone of societal progress,...          1
3     Computers, the backbone of modern technology, ...          1
4     Chess, a timeless game of strategy and intelle...          1
...                                                 ...        ...
2745  Generate a detailed summary of global healthca...          1
2746  Compose an in-depth exploration of financial t...          1
2747  Generate a detailed summary of autonomous vehi...          1
2748  Develop a persuasive argument about internet o...          1
2749  Generate a detailed summary of supply chain ma...          1

[2750 rows x 2 columns]

# Pre-processing

In [7]:
data['text']

0       Machine learning, a subset of artificial intel...
1       A decision tree, a prominent machine learning ...
2       Education, a cornerstone of societal progress,...
3       Computers, the backbone of modern technology, ...
4       Chess, a timeless game of strategy and intelle...
                              ...                        
2745    Generate a detailed summary of global healthca...
2746    Compose an in-depth exploration of financial t...
2747    Generate a detailed summary of autonomous vehi...
2748    Develop a persuasive argument about internet o...
2749    Generate a detailed summary of supply chain ma...
Name: text, Length: 2750, dtype: object

In [8]:
data = data.drop_duplicates()

In [9]:
#here we need to vecotorize text , bcz machine only understands binary lang , vecotorization will convert 
# it to numeric data , so machine will learn if datat is like this numeric data , it it ai generated(1)

In [10]:
#first we will split train and test data , and will vecorize only training data

In [11]:
import nltk 
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\khole\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\khole\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [12]:
# Initialize stopwords and lemmatizer
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

# Text cleaning function
def clean_text(text_):
    text_ = text_.lower()                           # Lowercasing
    text_ = re.sub(r'[^a-z\s]', '', text_)          # Remove punctuation, numbers
    tokens = text_.split()                         # Tokenization
    tokens = [word for word in tokens if word not in stop_words]  # Stopword removal
    tokens = [lemmatizer.lemmatize(word) for word in tokens]      # Lemmatization
    return " ".join(tokens)

# Apply cleaning to dataset
data['clean_text'] = data['text'].apply(clean_text)

# View results
data[['text', 'clean_text']].head()

C:\Users\khole\AppData\Local\Temp\ipykernel_56572\108913161.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['clean_text'] = data['text'].apply(clean_text)


text  \
0  Machine learning, a subset of artificial intel...   
1  A decision tree, a prominent machine learning ...   
2  Education, a cornerstone of societal progress,...   
3  Computers, the backbone of modern technology, ...   
4  Chess, a timeless game of strategy and intelle...   

                                          clean_text  
0  machine learning subset artificial intelligenc...  
1  decision tree prominent machine learning algor...  
2  education cornerstone societal progress extend...  
3  computer backbone modern technology revolution...  
4  chess timeless game strategy intellect transce...

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X = data['clean_text']
X

0       machine learning subset artificial intelligenc...
1       decision tree prominent machine learning algor...
2       education cornerstone societal progress extend...
3       computer backbone modern technology revolution...
4       chess timeless game strategy intellect transce...
                              ...                        
2745    generate detailed summary global healthcare co...
2746    compose indepth exploration financial technolo...
2747    generate detailed summary autonomous vehicle c...
2748    develop persuasive argument internet thing con...
2749    generate detailed summary supply chain managem...
Name: clean_text, Length: 2420, dtype: object

In [15]:
y = data['generated']
y

0       1
1       1
2       1
3       1
4       1
       ..
2745    1
2746    1
2747    1
2748    1
2749    1
Name: generated, Length: 2420, dtype: int64

In [16]:
d_concat = pd.concat([X,y] ,axis =1)
d_concat

clean_text  generated
0     machine learning subset artificial intelligenc...          1
1     decision tree prominent machine learning algor...          1
2     education cornerstone societal progress extend...          1
3     computer backbone modern technology revolution...          1
4     chess timeless game strategy intellect transce...          1
...                                                 ...        ...
2745  generate detailed summary global healthcare co...          1
2746  compose indepth exploration financial technolo...          1
2747  generate detailed summary autonomous vehicle c...          1
2748  develop persuasive argument internet thing con...          1
2749  generate detailed summary supply chain managem...          1

[2420 rows x 2 columns]

In [17]:
X_train , X_test , y_train , y_test = train_test_split(X,y , test_size = 0.2 , random_state=42 )

In [18]:
print(X_train)

1684    develop persuasive argument blockchain applica...
1571    draft technical report analyzing gene editing ...
545     america great past time might past isnt baseba...
1376    modern automobile axle wheel smog ridden conte...
1652    develop persuasive argument artificial intelli...
                              ...                        
1649    compile list key insight financial technology ...
1096    limiting car usage advantage many reason examp...
1131    may concern electoral college used electing pr...
1295    electoral college process put place founding f...
861     car always used get point point b people socie...
Name: clean_text, Length: 1936, dtype: object


In [19]:
print(X_test)

411     world today many people use motor vehicle get ...
200     everyday great many people drive car commute w...
1688    provide stepbystep guide history mathematics c...
1125    research done think changing system would good...
1356    dear president need get something chest need c...
                              ...                        
1576    develop persuasive argument financial technolo...
728     imagine president majority people voted win el...
282     limiting car usage could greatly benefit lifes...
2103    compile list key insight space exploration mis...
1622    create structured outline blockchain applicati...
Name: clean_text, Length: 484, dtype: object


In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    ngram_range=(1,2),      # Unigrams + Bigrams
    max_features=5000
)
#    stop_words   : removes common words like is , and ..
#    max_features = keeps top 5000 important words 

In [21]:
X_train_vectorized = vectorizer.fit_transform(X_train) 

#fit_transform learns vocabulary , and word importance 

X_test_vectorized = vectorizer.transform(X_test)

#transform : coverts into numeric values

print("TF-IDF Feature Matrix Shape:", X_train_vectorized.shape)
print("TF-IDF Feature Matrix Shape:", X_test_vectorized.shape)

print(X_train.shape)

TF-IDF Feature Matrix Shape: (1936, 5000)
TF-IDF Feature Matrix Shape: (484, 5000)
(1936,)


# Model fitting

# Random Forest

In [22]:
from sklearn.ensemble import RandomForestClassifier 
from sklearn.metrics import accuracy_score, classification_report , confusion_matrix

rf_model = RandomForestClassifier(n_estimators=150, random_state=42)
rf_model.fit(X_train_vectorized, y_train)

y_pred_rf = rf_model.predict(X_test_vectorized)

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nClassification Report:\n", classification_report(y_test, y_pred_rf))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))

Random Forest Accuracy: 0.9979338842975206

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       295
           1       1.00      0.99      1.00       189

    accuracy                           1.00       484
   macro avg       1.00      1.00      1.00       484
weighted avg       1.00      1.00      1.00       484


Confusion Matrix:
 [[295   0]
 [  1 188]]


# Support Vector Machine

In [23]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score ,classification_report,confusion_matrix

svm_model = LinearSVC()
svm_model.fit(X_train_vectorized, y_train)

y_pred_svm = svm_model.predict(X_test_vectorized)

print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))
print("\nClassification Report:\n", classification_report(y_test, y_pred_svm))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_svm))

SVM Accuracy: 0.9979338842975206

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       295
           1       1.00      0.99      1.00       189

    accuracy                           1.00       484
   macro avg       1.00      1.00      1.00       484
weighted avg       1.00      1.00      1.00       484


Confusion Matrix:
 [[295   0]
 [  1 188]]


# Logistic Regression 

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialize Logistic Regression model
lr_model = LogisticRegression(
    max_iter=2000,
    class_weight='balanced',
    random_state=42
)

# Train the model
lr_model.fit(X_train_vectorized, y_train)

# Predict on test data
y_pred_lr = lr_model.predict(X_test_vectorized)

# Evaluation
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print("\nClassification Report:\n", classification_report(y_test, y_pred_lr))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_lr))


Logistic Regression Accuracy: 0.9958677685950413

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       295
           1       0.99      0.99      0.99       189

    accuracy                           1.00       484
   macro avg       1.00      1.00      1.00       484
weighted avg       1.00      1.00      1.00       484


Confusion Matrix:
 [[294   1]
 [  1 188]]


In [25]:

def ai_gen_predictor():
    """
    Takes user text input and predicts whether it is
    AI-generated or Human-generated
    """

    # Take input
    text = input("Enter text to check: ")

    # Clean the text (same preprocessing as training)
    cleaned_text = clean_text(text)

    # Vectorize the text (convert to numeric form)
    text_vectorized = vectorizer.transform([cleaned_text])

    # Predict using trained SVM model
    prediction = rf_model.predict(text_vectorized)[0]

    # Return result
    if prediction == 0:
        return "Human Generated Text"
    else:
        return "AI Generated Text"


In [26]:
ai_gen_predictor()

'AI Generated Text'

In [27]:
import joblib
joblib.dump(rf_model , 'AI_generated_predictor.pkl')
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

['tfidf_vectorizer.pkl']